steps:
  - name: 'bash'
    script: |
      #!/bin/sh
      set -e
      set -x
      echo "Hello World"
    
  - name: 'bash'
    script: |
      #!/bin/sh
      set -e
      set -x
      docker --version
      docker compose version

options:
  logging: CLOUD_LOGGING_ONLY
